env: "gymma_continue"
mac: "basic_mac_continue" # Basic controller

env_args:
  key: null
  time_limit: 5000
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
